name: naturalist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9295444285962731
title: The Naturalist Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6710186151321977
  lightness: 0.4803736151661724
  saturation: 0.11036349786445498
  rhythmicContrast: 0.770834919065237
purpose: []
